# Basic build settings
[build]
  command = "npm run build"  # Specify the build command for your project
  # publish = "dist"          # Specify the directory to deploy

# Asset optimization and caching settings
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
  treeshake = true

[build.processing.images]
  compress = true
