# Basic build settings
[build]
  command = "npm run build"  # Specify the build command for your project
  # publish = "dist"          # Specify the directory to deploy

# Asset optimization and caching settings
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
  treeshake = true

[build.processing.images]
  compress = true


[[redirects]]
from = "/about"
to = "/team"
status = 301


[[redirects]]
from = "/knowledge-lab-team"
to = "/team"
status = 301


[[redirects]]
from = "/metaknowledge-research-network"
to = "/team"
status = 301


[[redirects]]
from = "/opportunities"
to = "/join"
status = 301


[[redirects]]
from = "/research"
to = "/initiatives"
status = 301

[[redirects]]
from = "/projects"
to = "/initiatives"
status = 301

[[redirects]]
from = "/metaknowledge-research-network"
to = "/team"
status = 301


[[redirects]]
from = "/alumni"
to = "/team"
status = 301

[[redirects]]
from = "/projects/*"
to = "/initiatives"
status = 301



